aoiVerion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-ingress
spec:
  rules:
  - host: myapp.com
    http:
      # Call services by its name
      paths:
      - backend:
        serviceName: myapp-service
        servicePort: 80
      - backend:
        serviceName: mongo-service
        servicePort: 27017
